coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080

# --- Memory tối thiểu cho 8GB RAM ---
query.max-memory=512MB
query.max-memory-per-node=512MB
catalog.management=dynamic
